//$file${.::mef_awg.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dpp.qm
// File:  ${.::mef_awg.c}
//
// This code has been generated by QM 7.0.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::mef_awg.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "mef_awg.h"
#include "awg.h"
#include "bsp.h"
#include "display.h"


//$declare${AOs_Awg::Awg} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs_Awg::Awg} ............................................................
typedef struct Awg {
// protected:
    QActive super;

// public:
    QTimeEvt time1segEvt;

// private:
    QTimeEvt time3segEvt;
} Awg;

extern Awg Awg_inst;
extern QEvt const Awg_avanc_evt;
extern QEvt const Awg_encoder_evt;
extern QEvt const Awg_init_evt;
extern QEvt const Awg_confirm_evt;
extern QEvt const  Awg_atras_evt;

extern QEvt const Awg_multiplicador_evt;

extern uint8_t Awg_StateConfig;

extern QEvt const  Awg_stop_evt;

// protected:
static QState Awg_initial(Awg * const me, void const * const par);
static QState Awg_Reset(Awg * const me, QEvt const * const e);
static QState Awg_Configuracion(Awg * const me, QEvt const * const e);
static QState Awg_Tipo_Func(Awg * const me, QEvt const * const e);
static QState Awg_Freq(Awg * const me, QEvt const * const e);
static QState Awg_Amplitud(Awg * const me, QEvt const * const e);
static QState Awg_Offset(Awg * const me, QEvt const * const e);
static QState Awg_Confirm_config(Awg * const me, QEvt const * const e);
static QState Awg_Salida(Awg * const me, QEvt const * const e);
//$enddecl${AOs_Awg::Awg} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared_Awg} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared_Awg::setEvt_Econder} ..............................................
void setEvt_Econder(void) {
    // Crear el evento ENCODER y enviarlo
    //QEvt *encoder_evt = Q_NEW(QEvt, ENCODER_SIG);  // Crear el evento con la señal ENCODER_SIG

    // Enviar el evento a la máquina de estados activa (AO: Active Object)
    //QACTIVE_POST(AO_Awg, &Awg_encoder_evt, 0);

    QACTIVE_POST(AO_Awg, &Awg_encoder_evt, 0);
}

//${Shared_Awg::setEvt_Confirm} ..............................................
void setEvt_Confirm(void) {
    QACTIVE_POST(AO_Awg, &Awg_confirm_evt, 0);
}

//${Shared_Awg::setEvt_Init} .................................................
void setEvt_Init(void) {
    QACTIVE_POST(AO_Awg, &Awg_init_evt, 0);
}

//${Shared_Awg::Awg_ctor} ....................................................
void Awg_ctor(void) {
    Awg * const me = &Awg_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Awg_initial));
    //QTimeEvt_ctorX(&me->time1segEvt, &me->super, TIMER_1SEG_SIG, 0U);
    QTimeEvt_ctorX(&me->time3segEvt, &me->super, TIMER_3SEG_SIG, 0U);
}

//${Shared_Awg::setEvt_Avanc} ................................................
void setEvt_Avanc(void) {
    QACTIVE_POST(AO_Awg, &Awg_avanc_evt, 0);
}

//${Shared_Awg::AO_Awg} ......................................................
QActive * const AO_Awg = &Awg_inst.super;

//${Shared_Awg::setEvt_Atras} ................................................
void setEvt_Atras(void) {
    QACTIVE_POST(AO_Awg, &Awg_atras_evt, 0);
}

//${Shared_Awg::setEvt_init} .................................................
void setEvt_init(void) {
    QACTIVE_POST(AO_Awg, &Awg_init_evt, 0);
}

//${Shared_Awg::setEvt_Multiplicador} ........................................
void setEvt_Multiplicador(void) {
    QACTIVE_POST(AO_Awg, &Awg_multiplicador_evt, 0);
}

//${Shared_Awg::getCurrentState} .............................................
uint8_t getCurrentState(void) {
    return Awg_StateConfig;
}

//${Shared_Awg::setEvtStop} ..................................................
void setEvtStop(void) {
    QACTIVE_POST(AO_Awg, &Awg_stop_evt, 0);
}
//$enddef${Shared_Awg} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs_Awg::Awg} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs_Awg::Awg} ............................................................
Awg Awg_inst;
QEvt const Awg_avanc_evt = QEVT_INITIALIZER(AVANC_SIG);

QEvt const Awg_encoder_evt = QEVT_INITIALIZER(ENCODER_SIG);

QEvt const Awg_init_evt = QEVT_INITIALIZER(INIT_SIG);

QEvt const Awg_confirm_evt = QEVT_INITIALIZER(CONFIRM_SIG);

QEvt const  Awg_atras_evt = QEVT_INITIALIZER(ATRAS_SIG);

QEvt const Awg_multiplicador_evt = QEVT_INITIALIZER(MULTIPLICADOR_SIG);

uint8_t Awg_StateConfig = CONFIG_FUNCION;

QEvt const  Awg_stop_evt = QEVT_INITIALIZER(STOP_SIG);


//${AOs_Awg::Awg::SM} ........................................................
static QState Awg_initial(Awg * const me, void const * const par) {
    //${AOs_Awg::Awg::SM::initial}
    // Display
    display_init();

    // Etapas
    awg_config();

    // Temporizador
    QTimeEvt_armX(&me->time3segEvt,
    7000, 0);
    return Q_TRAN(&Awg_Reset);
}

//${AOs_Awg::Awg::SM::Reset} .................................................
static QState Awg_Reset(Awg * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs_Awg::Awg::SM::Reset::INIT}
        case INIT_SIG: {
            // Temporizador
            QTimeEvt_disarm(&me->time3segEvt);

            // Display
            drawWaveform(0, 10, 1000, 0);
            display_func();
            display_freq();
            display_amp();
            display_offset();
            display_setMultiplicadorText("x1 Hz");
            status_ = Q_TRAN(&Awg_Configuracion);
            break;
        }
        //${AOs_Awg::Awg::SM::Reset::TIMER_3SEG}
        case TIMER_3SEG_SIG: {
            // Mef
            awg_reset();    // Lanza el evento INIT
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs_Awg::Awg::SM::Configuracion} .........................................
static QState Awg_Configuracion(Awg * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs_Awg::Awg::SM::Configuracion::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Awg_Tipo_Func);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs_Awg::Awg::SM::Configuracion::Tipo_Func} ..............................
static QState Awg_Tipo_Func(Awg * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs_Awg::Awg::SM::Configuracion::Tipo_Func}
        case Q_ENTRY_SIG: {
            Awg_StateConfig = CONFIG_FUNCION;
            awg_resetEnc();
            display_pulsarBoton(BOTON_FUNCTION, true);
            //printf("Estado: tipo de funcion.\n");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Tipo_Func}
        case Q_EXIT_SIG: {
            display_pulsarBoton(BOTON_FUNCTION, false);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Tipo_Func::AVANC}
        case AVANC_SIG: {
            status_ = Q_TRAN(&Awg_Freq);
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Tipo_Func::ENCODER}
        case ENCODER_SIG: {
            awg_Func();
            display_func();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Awg_Configuracion);
            break;
        }
    }
    return status_;
}

//${AOs_Awg::Awg::SM::Configuracion::Freq} ...................................
static QState Awg_Freq(Awg * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs_Awg::Awg::SM::Configuracion::Freq}
        case Q_ENTRY_SIG: {
            Awg_StateConfig = CONFIG_FREQ;
            awg_resetEnc();
            display_pulsarBoton(BOTON_FREQ, true);
            //printf("Estado: config freq.\n");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Freq}
        case Q_EXIT_SIG: {
            display_pulsarBoton(BOTON_FREQ, false);
            display_setMultiplicadorText("x1 Vp");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Freq::AVANC}
        case AVANC_SIG: {
            status_ = Q_TRAN(&Awg_Amplitud);
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Freq::ENCODER}
        case ENCODER_SIG: {
            awg_Freq();
            display_freq();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Freq::ATRAS}
        case ATRAS_SIG: {
            status_ = Q_TRAN(&Awg_Tipo_Func);
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Freq::MULTIPLICADOR}
        case MULTIPLICADOR_SIG: {
            awg_multiplicador(MULTIPLICADOR_FREQ);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Awg_Configuracion);
            break;
        }
    }
    return status_;
}

//${AOs_Awg::Awg::SM::Configuracion::Amplitud} ...............................
static QState Awg_Amplitud(Awg * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs_Awg::Awg::SM::Configuracion::Amplitud}
        case Q_ENTRY_SIG: {
            Awg_StateConfig = CONFIG_AMP;
            awg_resetEnc();
            display_pulsarBoton(BOTON_AMP, true);
            //printf("Estado: config Amp.\n");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Amplitud}
        case Q_EXIT_SIG: {
            display_pulsarBoton(BOTON_AMP, false);
            display_setMultiplicadorText("x1 Vp");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Amplitud::AVANC}
        case AVANC_SIG: {
            status_ = Q_TRAN(&Awg_Offset);
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Amplitud::ENCODER}
        case ENCODER_SIG: {
            // Señal
            awg_Amp();

            // Display
            display_amp();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Amplitud::ATRAS}
        case ATRAS_SIG: {
            status_ = Q_TRAN(&Awg_Freq);
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Amplitud::MULTIPLICADOR}
        case MULTIPLICADOR_SIG: {
            awg_multiplicador(MULTIPLICADOR_AMP);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Awg_Configuracion);
            break;
        }
    }
    return status_;
}

//${AOs_Awg::Awg::SM::Configuracion::Offset} .................................
static QState Awg_Offset(Awg * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs_Awg::Awg::SM::Configuracion::Offset}
        case Q_ENTRY_SIG: {
            Awg_StateConfig = CONFIG_OFFSET;
            awg_resetEnc();
            display_pulsarBoton(BOTON_OFFSET, true);
            //printf("Estado: config offset.\n");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Offset}
        case Q_EXIT_SIG: {
            display_pulsarBoton(BOTON_OFFSET, false);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Offset::ENCODER}
        case ENCODER_SIG: {
            awg_Offset();
            display_offset();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Offset::AVANC}
        case AVANC_SIG: {
            status_ = Q_TRAN(&Awg_Confirm_config);
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Offset::ATRAS}
        case ATRAS_SIG: {
            status_ = Q_TRAN(&Awg_Amplitud);
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Offset::MULTIPLICADOR}
        case MULTIPLICADOR_SIG: {
            awg_multiplicador(MULTIPLICADOR_OFFSET);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Awg_Configuracion);
            break;
        }
    }
    return status_;
}

//${AOs_Awg::Awg::SM::Configuracion::Confirm_config} .........................
static QState Awg_Confirm_config(Awg * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs_Awg::Awg::SM::Configuracion::Confirm_config}
        case Q_ENTRY_SIG: {
            Awg_StateConfig = CONFIG_CONFIRM;
            //printf("Estado: confirmacion config.\n");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Confirm_config}
        case Q_EXIT_SIG: {
            display_setMultiplicadorText("x1 Hz");
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Confirm_config::CONFIRM}
        case CONFIRM_SIG: {
            awg_enableOutput();
            display_pulsarBoton(BOTON_SALIDA, true);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Confirm_config::AVANC}
        case AVANC_SIG: {
            //${AOs_Awg::Awg::SM::Configuracion::Confirm_config::AVANC::[fin_config==1]}
            if (awg_reconfig() == 1) {
                status_ = Q_TRAN(&Awg_Salida);
            }
            //${AOs_Awg::Awg::SM::Configuracion::Confirm_config::AVANC::[fin_config==0]}
            else if (awg_reconfig() == 0) {
                status_ = Q_TRAN(&Awg_Tipo_Func);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        //${AOs_Awg::Awg::SM::Configuracion::Confirm_config::ATRAS}
        case ATRAS_SIG: {
            status_ = Q_TRAN(&Awg_Offset);
            break;
        }
        default: {
            status_ = Q_SUPER(&Awg_Configuracion);
            break;
        }
    }
    return status_;
}

//${AOs_Awg::Awg::SM::Salida} ................................................
static QState Awg_Salida(Awg * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs_Awg::Awg::SM::Salida}
        case Q_ENTRY_SIG: {
            Awg_StateConfig = SALIDA_EN;
            awg_start();
            //awg_display();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Salida}
        case Q_EXIT_SIG: {
            awg_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Salida::TIMER_1SEG}
        case TIMER_1SEG_SIG: {
            awg_blink();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs_Awg::Awg::SM::Salida::STOP}
        case STOP_SIG: {
            awg_stop();
            display_pulsarBoton(BOTON_SALIDA, true);
            status_ = Q_TRAN(&Awg_Tipo_Func);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs_Awg::Awg} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define ${AOs_Awg}
